### ISSUE TITLE
Had to create the backup folder for it to work on scripts(haven't tested on websites but it seems like the same)

### ISSUE THREAD

**Issue by SkylarPlayz348** [FAXES/easycompile#1]
I tested it out and i noticed that i was getting and error for it not being able to open up the backups folder so i looked thoroughly through the error and even looked at the index.js and noticed that it was looking for a folder that probably had nothing in it when you released it. To fix this i would just ad a text file named something like "This is where the backups go" to make sure this doesn't happen.

**Comment by braxtongpoll** [comment]
Didn't realize I did this when uploading the files, it's been fixed thanks for reporting.
