### ISSUE TITLE
non-functional translation problem

### ISSUE THREAD

**Issue by WolfCorp50** [FAXES/easycompile#11]
Hello, 
I've come to report a problem: the translation button doesn't work. It says interaction failed.

Thanks in advance, the command remains /settings other

Best regards,
![Screenshot_1](https://github.com/FAXES/easycompile/assets/153070698/2482954b-031a-4b5b-bbc4-dbf319aa23f8)

**Comment by FAXES** [comment]
[easycompile](https://github.com/FAXES/easycompile) isn't a Discord bot?
