### ISSUE TITLE
Invalid token.

### ISSUE THREAD

**Issue by Itz-Hyperz** [FAXES/easycompile#4]
When running it returns "invalid token".

main.js code:
```js
require('easycompile').changeExtension('.lol');
let run = require('./backend.lol');
run('hello world!');
```

backend.lol before compile:
```js
module.exports = function (bruh) {
    console.log(bruh)
};
```

error received:
![error](https://cdn.hyperz.net/main/ZUWuDG.png)

---

I noticed this happens due to the file extensions, while yes, you made a dynamic variable for `COMPILED_EXTNAME` in the index.js file of easycompile from [npm](https://npmjs.com/package/easycompile), but this doesn't work in basic Bytenode as it uses `Module._extensions` to set "what to do when" that file extension comes up.

By simply changing the extension name in `backend.lol` to `backend.easycompile` which is what is referenced in the default `COMPILED_EXTNAME` variable BEFORE it gets "set", then it will work fine with no issues.

![example](https://cdn.hyperz.net/main/GFpX0i.png)

Essentially, the problem is that you can't just change the `COMPILED_EXTNAME` variable with a function.

**Comment by braxtongpoll** [comment]
Please report issues on proper repositories.  See [here](https://github.com/FAXES/easycompile-npm).

**Comment by KillaNAdev** [comment]
> Please report issues on proper repositories. See [here](https://github.com/FAXES/easycompile-npm).

- 🤓

**Comment by KillaNAdev** [comment]
❌ Fix the issue.
✅ Complain about where he posts the issue at.
Is there still an issue. ✅ 
- Love you pluto

**Comment by FAXES** [comment]
> ❌ Fix the issue. ✅ Complain about where he posts the issue at. Is there still an issue. ✅
> 
> * Love you pluto

The issue was already being corrected before the issue was opened. Please keep a positive space on our platforms. Forms of harassment and negative communication that isn't constructive aren't welcome.

Cheers 🍻

**Comment by KillaNAdev** [comment]
Harssment = Me saying I love someone 😢 (MID SPELLING)

**Comment by FAXES** [comment]
Not what was directed. Our other platforms suggest differently.
