### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by SkylarPlayz348** [FAXES/easycompile#8]
So idk if I didn't get the memo or something but is there something else i need to do before compiling the script
![image](https://user-images.githubusercontent.com/73512621/157825417-811054af-471f-458c-9e69-59936922dfbc.png)

**Comment by FAXES** [comment]
The compiled file needs to be ran inside of a js file first with the easycompile package defined above the call. This makes the .easycompile extension register as a file type.

**Comment by Itz-Hyperz** [comment]
Your code should look like this in an `index.js` file:
```js
require('easycompile').changeExtension('.easycompile');
require('./index.easycompile');
```

then you can run `node index.js` in your terminal.

**Comment by SkylarPlayz348** [comment]
thanks all good now didn't understand the usage part of the readme

**Comment by FAXES** [comment]
> thanks all good now didn't understand the usage part of the readme

We'll work on updating that
